---
name: Build and import collection

on:
  push:
    branches: [devel]
  pull_request:

permissions:
  contents: read

jobs:
  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@fbf0452809057bf50d9e263f49de13ac789a747c # main
