---
name: Check changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@cbdec1f72eeee38b7e60d0f2346c66e622eea02a # main
