---
name: Check changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@c105d6b8b887a36219224da17adc7518aab2401d # main
