---
name: Check changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@2f18fdf5765dfdcd31781acb9c9b3206bc3f34ea # main
